# System-wide settings
system:
  environment: "development"
  log_level: "INFO"
  paths:
    data: "./data"
    cache: "./cache"
    logs: "./logs"
    temp: "./temp"
  monitoring:
    enabled: true
    metrics:
      - "response_time"
      - "memory_usage"
      - "api_calls"
    alert_thresholds:
      response_time: 5000  # ms
      memory_usage: 80     # percent

# Agent configurations
agents:
  notewriter:
    max_summary_length: 2000
    min_concept_relevance: 0.7
    complexity_levels: ["basic", "intermediate", "advanced"]
    summary_styles: ["concise", "detailed", "bullet_points"]
    
  planner:
    session_duration: 25  # minutes
    break_duration: 5     # minutes
    max_daily_hours: 8
    min_break_interval: 25
    scheduling_window: 7  # days
    priority_levels: ["high", "medium", "low"]
    
  advisor:
    feedback_interval: 15  # minutes
    progress_thresholds:
      low: 0.3
      medium: 0.6
      high: 0.8
    intervention_types:
      - "technique_suggestion"
      - "break_reminder"
      - "focus_check"
      - "encouragement"
      
  profile_analyzer:
    analysis_frequency: "daily"
    min_data_points: 5
    trend_window: 7  # days
    metrics:
      - "focus_duration"
      - "completion_rate"
      - "understanding_level"
      - "engagement_score"

# ADHD Support settings
adhd_support:
  session_settings:
    default_focus_duration: 25
    default_break_duration: 5
    long_break_duration: 15
    max_sessions_before_long_break: 4
    
  focus_monitoring:
    check_interval: 5  # minutes
    alert_threshold: 0.6
    intervention_threshold: 0.4
    monitoring_metrics:
      - "attention_level"
      - "task_switching"
      - "time_on_task"
      - "distraction_count"
    
  break_activities:
    active:
      - type: "physical"
        activities:
          - "quick stretching"
          - "short walk"
          - "jumping jacks"
        duration: 5
    relaxing:
      - type: "mental"
        activities:
          - "deep breathing"
          - "mindfulness minute"
          - "water break"
        duration: 3

# Vector store settings (Pinecone)
pinecone:
  environment: "gcp-starter"
  dimension: 384
  metric: "cosine"
  index_settings:
    name: "academic-assistant"
    pod_type: "starter"
    replicas: 1
    metadata_config:
      indexed: ["type", "subject", "difficulty"]

# Database settings 
neo4j:
  database: "neo4j"
  connection_settings:
    max_connection_lifetime: 3600
    max_connection_pool_size: 50
    connection_timeout: 30
    connection_acquisition_timeout: 60

# Cache settings
cache:
  enabled: true
  ttl: 3600
  max_size: 1000
  backends:
    - "memory"
    - "disk"
  policies:
    eviction: "lru"
    compression: true